# M12-L1 Problem 2

Sometimes the dimensionality is greater than the number of samples. For example,in this problem X has 19 features, but there are only 4 data points. You will need to use the alternate PCA formulation in this case. Follow the steps in the cells below to implement this method.

In [9]:
import numpy as np
import matplotlib.pyplot as plt

X = np.array([  [-2,  1,  2, -3,  4,  1,  0,  3,  0,  2,  1,  1,  2,  3, -2, -3, 2,  1,  0],
                [ 1,  2, -4,  2, -4,  2,  5,  2,  2,  1, -3,  0,  0,  1, -2,  1, 1, -3, -2],
                [ 1, -3,  2,  1,  0, -3, -5, -1,  3,  3, -2, -3, -2, -1,  1,  0, 5,  4,  2],
                [ 3, -1,  0,  2,  2, -5, -4, -1,  2, -1,  3,  4,  4,  2,  1,  2, -2,  1, -1]])


## Computing Principal Components

### The A matrix

First, you should compute the `A` matrix, where A is $(X-\mu)'$. (Note the transpose)

Print this matrix below. It should have size $19\times 4$.

In [10]:
# YOUR CODE GOES HERE
A = X.T
print("A = \n", A)

A = 
 [[-2  1  1  3]
 [ 1  2 -3 -1]
 [ 2 -4  2  0]
 [-3  2  1  2]
 [ 4 -4  0  2]
 [ 1  2 -3 -5]
 [ 0  5 -5 -4]
 [ 3  2 -1 -1]
 [ 0  2  3  2]
 [ 2  1  3 -1]
 [ 1 -3 -2  3]
 [ 1  0 -3  4]
 [ 2  0 -2  4]
 [ 3  1 -1  2]
 [-2 -2  1  1]
 [-3  1  0  2]
 [ 2  1  5 -2]
 [ 1 -3  4  1]
 [ 0 -2  2 -1]]


### "Small" covariance matrix

By transposing $X-\mu$ to get $A$, now we can compute a smaller covariance matrix with $A' A$. Compute this matrix, `C`, below and print the result.

In [11]:
# YOUR CODE GOES HERE
C = np.cov(A)
print("C = \n", C)

C = 
 [[  4.25        -1.75        -2.           4.5         -2.5
   -4.75        -3.          -3.41666667   1.91666667  -2.25
    0.91666667   1.83333333   1.          -1.25         2.5
    4.33333333  -2.83333333  -0.08333333  -0.75      ]
 [ -1.75         4.91666667  -4.          -1.16666667  -1.83333333
    5.91666667   9.33333333   3.91666667  -1.75        -0.91666667
   -0.75         2.16666667   1.66666667   2.41666667  -3.5
   -1.          -2.5         -5.75        -3.08333333]
 [ -2.          -4.           8.          -4.           8.
   -4.         -10.          -1.33333333  -0.66666667   2.
    3.33333333  -1.33333333   0.           0.           2.
   -3.33333333   3.33333333   7.33333333   4.        ]
 [  4.5         -1.16666667  -4.           5.66666667  -5.66666667
   -3.16666667  -0.33333333  -3.16666667   2.5         -1.83333333
   -1.5          0.33333333  -0.66666667  -2.16666667   2.
    5.          -2.          -1.5         -1.16666667]
 [ -2.5         -1.83333333  

### Finding nonzero eigenvectors
Next, find the useful (nonzero) eigenvectors of `C`. 

For validation purposes, there should be 3 useful eigenvectors, and the first one is `[-0.06628148 -0.79038331 0.47285044 0.38381435]`. 

Keep these eigenvectors in a $4\times 3$ array `e`.

In [12]:
# YOUR CODE GOES HERE
w, v = np.linalg.eig(C) 
e = v[:, :3] 
print("\nUseful Eigenvectors, e:\n", e)


Useful Eigenvectors, e:
 [[-0.07294372+0.j -0.12277459+0.j  0.33008441+0.j]
 [ 0.26034151+0.j -0.11787331+0.j -0.11677714+0.j]
 [-0.29998485+0.j  0.09606164+0.j -0.27776956+0.j]
 [ 0.01067529+0.j -0.04536213+0.j  0.42516696+0.j]
 [-0.27653993+0.j -0.17530224+0.j -0.44157072+0.j]
 [ 0.37621372+0.j  0.15082188+0.j -0.23925816+0.j]
 [ 0.59257956+0.j -0.02265222+0.j -0.05657115+0.j]
 [ 0.19897063+0.j  0.0037123 +0.j -0.250194  +0.j]
 [-0.04569305+0.j  0.07236581+0.j  0.20213547+0.j]
 [-0.0084373 +0.j  0.25979087+0.j -0.10504274+0.j]
 [-0.18948616+0.j -0.35382298+0.j -0.1518308 +0.j]
 [-0.00380575+0.j -0.46650428+0.j -0.03585222+0.j]
 [-0.03449119+0.j -0.40571147+0.j -0.10256065+0.j]
 [ 0.05241297+0.j -0.20419008+0.j -0.19442141+0.j]
 [-0.19396809+0.j -0.00756997+0.j  0.16057937+0.j]
 [-0.01329023+0.j -0.11639359+0.j  0.36617258+0.j]
 [-0.0508452 +0.j  0.45626561+0.j -0.08985059+0.j]
 [-0.3456779 +0.j  0.16842745+0.j -0.07563409+0.j]
 [-0.16171488+0.j  0.18371276+0.j -0.0569842 +0.j]]


### Calculating "eigenfaces"

Now, we have all we need to compute `U`, the matrix of eigenfaces.

$\bf{U}_i = \bf{A} \bf{e}_i$  

$(19 \times 3) = (19 \times 4)(4 \times 3)$

Compute and print U. Be sure to normalize your eigenvectors `e` before using the above equation.

In [13]:
# YOUR CODE GOES HERE
e = e / np.linalg.norm(e, axis=0)
# Calculating "eigenfaces"
U = X.dot(e)
print("Eigenfaces, U:\n",U)

Eigenfaces, U:
 [[-0.50027219+0.j -0.36282393+0.j -8.2252748 +0.j]
 [ 9.09376778+0.j  0.80762958+0.j  3.41879818+0.j]
 [-7.64353981+0.j  7.46882498+0.j  2.19772875+0.j]
 [-6.46384972+0.j -7.60093701+0.j  2.91229504+0.j]]


## Projecting data into 3D

Now project your data into 3 dimensions with the formula: 

$\Omega = U^\text{T} A $  

$(3 \times 4) = (3 \times 19)(19 \times 4)$

Call the projected data $\Omega$ "`W`". Print `W.T`

In [14]:
# YOUR CODE GOES HERE
W = U.T.dot(X)
print('Projected data in 3 dimensions:\n',W.T)

Projected data in 3 dimensions:
 [[-16.94077683+0.j -13.8007086 +0.j  30.80396166+0.j]
 [ 47.08173252+0.j -13.5531027 +0.j -10.89315974+0.j]
 [-52.66269511+0.j  10.98148378+0.j -25.73028483+0.j]
 [ -0.88288713+0.j  -5.02931809+0.j  39.5357396 +0.j]
 [-51.30385933+0.j -19.88368804+0.j -40.75170186+0.j]
 [ 72.93713142+0.j  16.85064533+0.j -22.5423399 +0.j]
 [109.54193684+0.j  -2.90222897+0.j  -5.54383302+0.j]
 [ 30.79410854+0.j   0.65889941+0.j -22.94825184+0.j]
 [-17.6707833 +0.j   8.81986009+0.j  19.2553727 +0.j]
 [ -8.37354628+0.j  30.08939368+0.j  -9.3508602 +0.j]
 [-31.8860451 +0.j -40.52617365+0.j -14.14024174+0.j]
 [ -3.42505167+0.j -53.17304689+0.j  -3.16928091+0.j]
 [-11.56886366+0.j -46.06704584+0.j  -9.19682695+0.j]
 [  2.30879158+0.j -22.95154119+0.j -17.6301649 +0.j]
 [-31.29438072+0.j  -1.02172334+0.j  14.72297703+0.j]
 [ -2.33311511+0.j -13.30577265+0.j  33.91921267+0.j]
 [-17.19677617+0.j  52.62798065+0.j  -7.86769773+0.j]
 [-64.81958448+0.j  19.48865025+0.j  -6.77845929+

## Reconstructing data in 19-D

We can project the transformed data `W` back into the original 19-D space using:

$\Gamma_f = U \Omega + \Psi$   
where:  
$\Gamma_f = $ reconstructed data  
$U = $ eigenfaces  
$\Omega = $ Reduced data  
$\Psi = $ Means  

Do this, and compute the MSE between each reconstructed sample and corresponding original points. Report all 4 MSE values.




In [15]:
# YOUR CODE GOES HERE
X_reconstructed = U.dot(W) + np.mean(X, axis=0)
MSE = np.mean((X - X_reconstructed)**2, axis=1)
for i in range(4):
    print("MSE for sample %d: %e" %(i+1,MSE[i]))

MSE for sample 1: 3.039550e+04
MSE for sample 2: 1.509414e+05
MSE for sample 3: 1.444565e+05
MSE for sample 4: 1.162936e+05


C:\Users\srech\AppData\Local\Temp\ipykernel_20576\1018759787.py:5: ComplexWarning: Casting complex values to real discards the imaginary part
  print("MSE for sample %d: %e" %(i+1,MSE[i]))


## 2-D Reconstruction


What if we had only used the first 2 eigenvectors to compute the eigenfaces?
Below, redo the earlier calculations, but use only two eigenfaces. Compute the 4 MSE values that you would get in this case.

(You should get an MSE of 3.626 for the first sample.)

In [16]:
# YOUR CODE GOES HERE
e_2d = v[:, :2]  
e_2d = e_2d / np.linalg.norm(e_2d, axis=0)
U_2d = X.dot(e_2d)
W_2d = U_2d.T.dot(X)
X_reconstructed_2d = U_2d.dot(W_2d) + np.mean(X, axis=0)
MSE2 = np.mean((X - X_reconstructed_2d)**2, axis=1)
print("Using only 2 eigenvectors:")
for i in range(4):
    print("MSE for sample %d: %e" %(i+1,MSE2[i]))

Using only 2 eigenvectors:
MSE for sample 1: 5.451620e+02
MSE for sample 2: 1.462161e+05
MSE for sample 3: 1.420665e+05
MSE for sample 4: 1.122849e+05


C:\Users\srech\AppData\Local\Temp\ipykernel_20576\2260735766.py:10: ComplexWarning: Casting complex values to real discards the imaginary part
  print("MSE for sample %d: %e" %(i+1,MSE2[i]))
